spring.application.name=vendasse
spring.datasource.url=jdbc:postgresql://localhost:5432/vendasse
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.session.jdbc.initialize-schema=always
